version: '2'

services:
  ros:
    build: .
    network_mode: host
    user: "docker"
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - "ROS_IP=$ROS_IP"
      - "ROS_MASTER_URI=$ROS_MASTER_URI"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $PWD/catkin_ws:/home/docker/catkin_ws
    command: stdbuf -o L roscore
    restart: always
