version: '2'

services:
  ros2:
    build:
      context: .
      dockerfile: ros2_cuda.Dockerfile
    network_mode: host
    privileged: true
    ipc: host
    user: "docker"
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - "ROS_IP=$ROS_IP"
      - "ROS_MASTER_URI=$ROS_MASTER_URI"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/silvis/.ssh:/home/docker/.ssh
      - $PWD/colcon_ws:/home/docker/colcon_ws
      - $PWD/data:/home/docker/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: tail -f /dev/null
    restart: always
